stages:
  - build_environment
  - syntax_check
  - compiler
  - buildimg
  - deployment

cache:
  paths:
    - gotele/
  policy: pull-push

build:
  stage: build_environment
  tags:
  - build_env
  script:
  - sudo apt-get update && sudo apt-get upgrade -y
  - sudo apt-get install python3-pip -y
  - sudo pip3 install --upgrade pip
  - sudo pip3 install virtualenv
  - virtualenv gotele
  - source gotele/bin/activate

yaml:
  stage: syntax_check
  tags:
  - syntax_check
  script:
  - sudo pip3 install yamllint
  - yamllint ping-probes/var/targets.yaml
  - yamllint tcp-probes/var/targets.yaml

json:
  stage: syntax_check
  tags:
  - syntax_check
  script:
  - sudo apt-get install nodejs-legacy -y
  - sudo apt-get install npm -y
  - sudo npm install jsonlint -g
  - jsonlint ping-probes/.credentials.json
  - jsonlint tcp-probes/.credentials.json

Dockerfile:
  stage: syntax_check
  tags:
  - syntax_check
  script:
  - wget -cO hadolint https://github.com/hadolint/hadolint/releases/download/v1.13.0/hadolint-Linux-x86_64
  - chmod +x hadolint
  - ./hadolint tcp-probes/Dockerfile
  - ./hadolint ping-probes/Dockerfile

go_build:
  stage: compiler
  tags:
  - compiler
  script:
  - wget https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz
  - sudo tar -C /usr/local -xzf go1.11.2.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - export GOPATH=$PWD
  - go get -d -v github.com/influxdata/influxdb/client/v2
  - go get -d -v gopkg.in/yaml.v2
  - go install -v src/ping/credentials/credentials.go
  - go install -v src/ping/parser/json_parser_alpine.go
  - go install -v src/ping/cmd/ping_cmd_alpine.go
  - go install -v src/ping/yaml/yaml.go
  - go build -v src/ping/main.go
  - rm go1.11.2.linux-amd64.tar.gz

docker_build:
  stage: docker_build
  tags:
  - docker_build
  script:
  - sudo apt-get remove docker docker-engine docker.io -y
  - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update && sudo apt-get install docker-ce -y
  - echo $DOCKER_PASSWORD | sudo docker login -u=federico87 --password-stdin
  - sudo docker build ./ -t GO_network_telemetry_ping:latest
  - sudo docker tag GO_network_telemetry_ping federico87/GO_network_telemetry_ping
  - sudo docker push federico87/GO_network_telemetry_ping

remove ping container:
  stage: pre_deployment
  tags:
  - deployment
  script:
  - ssh -i "~/.aws.pem" ec2-user@ec2-18-130-13-134.eu-west-2.compute.amazonaws.com "sudo docker rm -f GO-ping"
  allow_failure: true


deploy new containers:
  stage: deployment
  tags:
  - deployment
  script:
  - ssh -i "~/.aws.pem" ec2-user@ec2-18-130-13-134.eu-west-2.compute.amazonaws.com "sudo docker run -d --name=ping --link db --restart=always federico87/GO_network_telemetry_ping"
  - ssh -i "~/.aws.pem" ec2-user@ec2-18-130-13-134.eu-west-2.compute.amazonaws.com "/usr/bin/python3 ~/ping-probes/dashboard_provisioning.py"
